version: '3.5'
services:
  app1:
    image: teohen/redis-pub-sub:local
    hostname: app1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    expose:
      - '8081'
    deploy:
      resources:
        limits: 
          cpus: '1.0'
          memory: '1.0GB'
  app2:
    image: teohen/redis-pub-sub:local
    hostname: app2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    expose:
      - '8082'
    deploy:
      resources:
        limits: 
          cpus: '1.0'
          memory: '1.0GB'
  redis:
    image: redis:latest
    hostname: redis
    command: redis-server --save "" --appendonly no
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1.0GB'


